version: '2'
services:
  minidlna:
    # https://github.com/besn0847/arm-minidlna
    image: besn0847/arm-minidlna
    restart: always
    volumes:
      - ${CACHE}:/data/db
      - ${DATA}:/data/media
    ports:
      - "8200:8200"
      - "1900:1900/udp"
  transmission:
    image: ewnd9/rpi-transmission
    restart: always
    volumes:
      - ${DATA}:/var/lib/transmission-daemon/downloads
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
  error-board:
    build: ./provision/docker/rpi-error-board
    restart: always
    ports:
      - "5000:3000"
    volumes:
      - ${DB}:/db
  app:
    # image: ewnd9/media-center:0.1.18
    build: ./
    restart: always
    ports:
      - "4000:3000"
    volumes:
      - ${DATA}:/data
      - ${DB}:/db
      - ${HOME}/.yarn-cache:/root/.yarn-cache
    links:
      - minidlna
    environment:
      - NODE_ENV=production
      - MC_X11_SUPPORT=true
      - MEDIA_PATH=/data
      - DATA_PATH=/db
      - TRAKT_TOKEN=${TRAKT_TOKEN}
      - ERROR_BOARD_URL=${ERROR_BOARD_URL}
    devices:
      - "/dev/vchiq:/dev/vchiq"
      - "/dev/fb0:/dev/fb0"
